--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-08-02 09:50:05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 25614)
-- Name: item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255)
);


ALTER TABLE public.item OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 25613)
-- Name: item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4790 (class 0 OID 25614)
-- Dependencies: 219
-- Data for Name: item; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.item (id, description, name) VALUES (2, 'beanboozled ', 'fake leather');
INSERT INTO public.item (id, description, name) VALUES (1, 'animal hide', 'leather');
INSERT INTO public.item (id, description, name) VALUES (3, 'finest animal skin ', 'real leather');
INSERT INTO public.item (id, description, name) VALUES (5, 'a rare ore', 'silver ore');
INSERT INTO public.item (id, description, name) VALUES (4, 'This is a rock', 'Rock');


--
-- TOC entry 4796 (class 0 OID 0)
-- Dependencies: 218
-- Name: item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_id_seq', 6, true);


--
-- TOC entry 4645 (class 2606 OID 25620)
-- Name: item item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (id);


-- Completed on 2024-08-02 09:50:06

--
-- PostgreSQL database dump complete
--

