--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-08-02 09:51:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 25622)
-- Name: warehouse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse (
    max_capacity integer NOT NULL,
    id bigint NOT NULL,
    location character varying(255),
    name character varying(255),
    owner character varying(255),
    CONSTRAINT warehouse_max_capacity_check CHECK ((max_capacity >= 0))
);


ALTER TABLE public.warehouse OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 25621)
-- Name: warehouse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warehouse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4791 (class 0 OID 25622)
-- Dependencies: 221
-- Data for Name: warehouse; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.warehouse (max_capacity, id, location, name, owner) VALUES (2000, 1, 'Rainbow', 'Warehouse1', 'Bill');
INSERT INTO public.warehouse (max_capacity, id, location, name, owner) VALUES (1242, 14, 'Mountains', 'Rocks Rocks Rocks', 'Old Rock');
INSERT INTO public.warehouse (max_capacity, id, location, name, owner) VALUES (123, 13, 'Builder Village', 'Tools', 'Bob');
INSERT INTO public.warehouse (max_capacity, id, location, name, owner) VALUES (3000, 12, 'Apple Village', 'Food', 'Juice');


--
-- TOC entry 4797 (class 0 OID 0)
-- Dependencies: 220
-- Name: warehouse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_id_seq', 14, true);


--
-- TOC entry 4646 (class 2606 OID 25629)
-- Name: warehouse warehouse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse
    ADD CONSTRAINT warehouse_pkey PRIMARY KEY (id);


-- Completed on 2024-08-02 09:51:24

--
-- PostgreSQL database dump complete
--

